language: python
python:
  - "3.4"
  - "3.5"

install: "pip install -r requirements.txt"

script: nosetests

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres