language: python
python:
  - "3.4"
  - "3.5"

install: "pip install -r requirements.txt"

script: nosetests

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
    - TEST_DATABASE_URL=postgresql://postgres:@localhost/travis_ci_test
    - CONFIG_NAME=testing
