"""empty message

Revision ID: d5c41039e31a
Revises: None
Create Date: 2016-06-02 01:27:05.899737

"""

# revision identifiers, used by Alembic.
revision = 'd5c41039e31a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Unicode(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agency_tag'), 'agency', ['tag'], unique=True)
    op.create_table('stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('title', sa.Unicode(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stop_latitude'), 'stop', ['latitude'], unique=False)
    op.create_index(op.f('ix_stop_longitude'), 'stop', ['longitude'], unique=False)
    op.create_index(op.f('ix_stop_tag'), 'stop', ['tag'], unique=False)
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_tag'), 'route', ['tag'], unique=False)
    op.create_table('route_stop',
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_stop')
    op.drop_index(op.f('ix_route_tag'), table_name='route')
    op.drop_table('route')
    op.drop_index(op.f('ix_stop_tag'), table_name='stop')
    op.drop_index(op.f('ix_stop_longitude'), table_name='stop')
    op.drop_index(op.f('ix_stop_latitude'), table_name='stop')
    op.drop_table('stop')
    op.drop_index(op.f('ix_agency_tag'), table_name='agency')
    op.drop_table('agency')
    ### end Alembic commands ###
